name: Deploy DAB

on:
  push:
    branches:
      - main

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      #################################################
      # Validate in Sales Workspace
      #################################################

      - name: Validate Bundle in Sales
        env:
          DATABRICKS_HOST: ${{ secrets.SALES_DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.SALES_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.SALES_CLIENT_SECRET }}
        run: |
          databricks bundle validate -t Sales

      - name: Deploy Bundle to Default
        env:
          DATABRICKS_HOST: ${{ secrets.DEFAULT_DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DEFAULT_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DEFAULT_CLIENT_SECRET }}
        run: |
          databricks bundle deploy -t default
